server:
  port: 8081

spring:
  jpa:
    # 应用启动时是否自动建表，默认为false
    generate-ddl: true
    # 是否在控制台显示SQL语句，默认为false
    show-sql: true
    # 设置应用启动时不重新建表
    hibernate:
      ddl-auto: none

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: 1234

logging:
  # 设置日志输出格式
  pattern:
    console: level-%level %msg%n
  level:
    root: info   # Spring Boot启动时的日志级别
    org.hibernate: info  # Hibernate运行日志级别
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.kaikeba.provider: debug
